//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NTR2017Model", "FK_DayEventForUser", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CalendarWithBase.Users), "DayEvents", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CalendarWithBase.DayEvents), true)]

#endregion

namespace CalendarWithBase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CalendarDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CalendarDatabaseEntities object using the connection string found in the 'CalendarDatabaseEntities' section of the application configuration file.
        /// </summary>
        public CalendarDatabaseEntities() : base("name=CalendarDatabaseEntities", "CalendarDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CalendarDatabaseEntities object.
        /// </summary>
        public CalendarDatabaseEntities(string connectionString) : base(connectionString, "CalendarDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CalendarDatabaseEntities object.
        /// </summary>
        public CalendarDatabaseEntities(EntityConnection connection) : base(connection, "CalendarDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DayEvents> DayEvents
        {
            get
            {
                if ((_DayEvents == null))
                {
                    _DayEvents = base.CreateObjectSet<DayEvents>("DayEvents");
                }
                return _DayEvents;
            }
        }
        private ObjectSet<DayEvents> _DayEvents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DayEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDayEvents(DayEvents dayEvents)
        {
            base.AddObject("DayEvents", dayEvents);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NTR2017Model", Name="DayEvents")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DayEvents : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DayEvents object.
        /// </summary>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="eventDescription">Initial value of the eventDescription property.</param>
        /// <param name="startTime">Initial value of the startTime property.</param>
        /// <param name="endTime">Initial value of the endTime property.</param>
        public static DayEvents CreateDayEvents(global::System.String username, global::System.String eventDescription, global::System.DateTime startTime, global::System.DateTime endTime)
        {
            DayEvents dayEvents = new DayEvents();
            dayEvents.username = username;
            dayEvents.eventDescription = eventDescription;
            dayEvents.startTime = startTime;
            dayEvents.endTime = endTime;
            return dayEvents;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                if (_username != value)
                {
                    OnusernameChanging(value);
                    ReportPropertyChanging("username");
                    _username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("username");
                    OnusernameChanged();
                }
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eventDescription
        {
            get
            {
                return _eventDescription;
            }
            set
            {
                if (_eventDescription != value)
                {
                    OneventDescriptionChanging(value);
                    ReportPropertyChanging("eventDescription");
                    _eventDescription = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("eventDescription");
                    OneventDescriptionChanged();
                }
            }
        }
        private global::System.String _eventDescription;
        partial void OneventDescriptionChanging(global::System.String value);
        partial void OneventDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime startTime
        {
            get
            {
                return _startTime;
            }
            set
            {
                if (_startTime != value)
                {
                    OnstartTimeChanging(value);
                    ReportPropertyChanging("startTime");
                    _startTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("startTime");
                    OnstartTimeChanged();
                }
            }
        }
        private global::System.DateTime _startTime;
        partial void OnstartTimeChanging(global::System.DateTime value);
        partial void OnstartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime endTime
        {
            get
            {
                return _endTime;
            }
            set
            {
                if (_endTime != value)
                {
                    OnendTimeChanging(value);
                    ReportPropertyChanging("endTime");
                    _endTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("endTime");
                    OnendTimeChanged();
                }
            }
        }
        private global::System.DateTime _endTime;
        partial void OnendTimeChanging(global::System.DateTime value);
        partial void OnendTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NTR2017Model", "FK_DayEventForUser", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("NTR2017Model.FK_DayEventForUser", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("NTR2017Model.FK_DayEventForUser", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("NTR2017Model.FK_DayEventForUser", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("NTR2017Model.FK_DayEventForUser", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NTR2017Model", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="username">Initial value of the username property.</param>
        public static Users CreateUsers(global::System.String username)
        {
            Users users = new Users();
            users.username = username;
            return users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                if (_username != value)
                {
                    OnusernameChanging(value);
                    ReportPropertyChanging("username");
                    _username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("username");
                    OnusernameChanged();
                }
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NTR2017Model", "FK_DayEventForUser", "DayEvents")]
        public EntityCollection<DayEvents> DayEvents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DayEvents>("NTR2017Model.FK_DayEventForUser", "DayEvents");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DayEvents>("NTR2017Model.FK_DayEventForUser", "DayEvents", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
